### ISSUE TITLE
Type 테이블에 Count 수 증가시키기

### ISSUE THREAD

**Issue by wnstjd5408** [wnstjd5408/flower#62]
### Comment
Flower가 한개씩 추가 될 때마다 수량을 한개 씩 증가를 시킵니다.

### TODO

- [x] 등록시 typeId를 받아서 수량을 증가시킵니다.
- [x] Type Entity에 수량 증가 메서드 추가
- [x] FlowerService에 저장시 수량 추가
- [x] 테스트
